=== scev0/x-source/libraries/influenceconfigurations.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:simpleType name="idstring">
    <xs:restriction base="xs:string">
      <xs:pattern value="[a-zA-Z_][a-zA-Z0-9_]*" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="influencelookup">
    <xs:restriction base="xs:string">
      <xs:enumeration value="hulldamage">
        <xs:annotation>
          <xs:documentation>
            Does direct hull damage. Multiple influences of this type add up.
          </xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="shielddamage">
        <xs:annotation>
          <xs:documentation>
            Does shield damage. Multiple influences of this type add up.
          </xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="hullshielddamage">
        <xs:annotation>
          <xs:documentation>
            Does damage first to shields, then hull. Multiple influences of this type add up.
          </xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="hullnoshielddamage">
        <xs:annotation>
          <xs:documentation>
            Does hull damage only if shields are down. Multiple influences of this type add up.
          </xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="hullrepair">
        <xs:annotation>
          <xs:documentation>
            Repairs hull damage. Multiple influences of this type add up.
          </xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="shieldrepair">
        <xs:annotation>
          <xs:documentation>
            Recharges shields. Multiple influences of this type add up.
          </xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="maxforwardspeed">
        <xs:annotation>
          <xs:documentation>
            Multiplier to maximum forward speed. Multiple influences of this type are multiplied together.
          </xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="maxreversespeed">
        <xs:annotation>
          <xs:documentation>
            Multiplier to maximum reverse speed. Multiple influences of this type are multiplied together.
          </xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="maxstrafespeed">
        <xs:annotation>
          <xs:documentation>
            Multiplier to maximum strafe speeds (both directions). Multiple influences of this type are multiplied together.
          </xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="maxsteeringspeed">
        <xs:annotation>
          <xs:documentation>
            Multiplier to maximum steering speeds (all directions). Multiple influences of this type are multiplied together.
          </xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="forwardacceleration">
        <xs:annotation>
          <xs:documentation>
            Multiplier to forward acceleration. Multiple influences of this type are multiplied together.
          </xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="reverseacceleration">
        <xs:annotation>
          <xs:documentation>
            Multiplier to reverse acceleration. Multiple influences of this type are multiplied together.
          </xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="strafeacceleration">
        <xs:annotation>
          <xs:documentation>
            Multiplier to strafe accelerations (both directions). Multiple influences of this type are multiplied together.
          </xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="steeringacceleration">
        <xs:annotation>
          <xs:documentation>
            Multiplier to steering accelerations (all directions). Multiple influences of this type are multiplied together.
          </xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="radarrange">
        <xs:annotation>
          <xs:documentation>
            Multiplier to radar range. Multiple influences of this type are multiplied together.
          </xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="radarcloak">
        <xs:annotation>
          <xs:documentation>
            Multiplier to radar cloaking. Note that a value of 1 means no cloaking and 0 means full cloaking. Multiple influences of this type are multiplied together.
          </xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="disableboost">
        <xs:annotation>
          <xs:documentation>
            Disable boosting for the duration of the profile. Multiple influences of this type do not make the effect any stronger.
          </xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="disabletravel">
        <xs:annotation>
          <xs:documentation>
            Disable travel mode for the duration of the profile. Multiple influences of this type do not make the effect any stronger.
          </xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="disableshooting">
        <xs:annotation>
          <xs:documentation>
            Disable shooting weapons for the duration of the profile. Multiple influences of this type do not make the effect any stronger.
          </xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="chargeoxygen">
        <xs:annotation>
          <xs:documentation>
            Recharges oxygen. Multiple influences of this type add up.
          </xs:documentation>
        </xs:annotation>
      </xs:enumeration>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="profilelookup">
    <xs:restriction base="xs:string">
      <xs:enumeration value="envelope">
        <xs:annotation>
          <xs:documentation>
            Envelope profile. Relevant properties: startvalue, sustianvalue, endvalue, delay, attackduration, sustainduration, releaseduration.
          </xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="continuous">
        <xs:annotation>
          <xs:documentation>
            Continuous profile. Relevant properties: startvalue, duration.
          </xs:documentation>
        </xs:annotation>
      </xs:enumeration>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="profile">
    <xs:annotation>
      <xs:documentation>
        The time-dependent profile of this influence. Used properties depend on profile type, see individual documentation.
      </xs:documentation>
    </xs:annotation>
    <xs:attribute name="type" type="profilelookup" use="required">
      <xs:annotation>
        <xs:documentation>
          Profile type
        </xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="startvalue" type="xs:float">
      <xs:annotation>
        <xs:documentation>
          [Envelope and continuous profile] The start value of the profile. Used while the current time is earlier than the start time.
        </xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="sustainvalue" type="xs:float">
      <xs:annotation>
        <xs:documentation>
          [Envelope profile] The value during the sustain part of the profile.
        </xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="endvalue" type="xs:float">
      <xs:annotation>
        <xs:documentation>
          [Envelope profile] The end value of the profile. Used when the current time is later than the end time.
        </xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="attackduration" type="xs:float">
      <xs:annotation>
        <xs:documentation>
          [Envelope profile] The time over which the value will interpolate between startvalue and sustainvalue. Defaults to 0.
        </xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="sustainduration" type="xs:float">
      <xs:annotation>
        <xs:documentation>
          [Envelope profile] The time over which the value will remain at the sustainvalue. Defaults to 0.
        </xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="releaseduration" type="xs:float">
      <xs:annotation>
        <xs:documentation>
          [Envelope profile] The time over which the value will interpolate between sustainvalue and endvalue. Defaults to 0.
        </xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="duration" type="xs:float">
      <xs:annotation>
        <xs:documentation>
          [Continuous profile] The total duration of this profile. Defaults to 0.
        </xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="delay" type="xs:float">
      <xs:annotation>
        <xs:documentation>
          [Envelope profile] The initial time delay before the attack phase starts. Defaults to 0.
        </xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:complexType>

  <xs:complexType name="influence">
    <xs:annotation>
      <xs:documentation>
        Influence
      </xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="profile" type="profile" minOccurs="1" maxOccurs="1" />
    </xs:sequence>
    <xs:attribute name="type" type="influencelookup">
      <xs:annotation>
        <xs:documentation>
          Influence type
        </xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:complexType>

  <xs:complexType name="influences">
    <xs:annotation>
      <xs:documentation>
        Influences, potentially for specific target classes
      </xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="influence" type="influence" minOccurs="1" maxOccurs="unbounded" />
    </xs:sequence>
    <xs:attribute name="classes" type="xs:string">
      <xs:annotation>
        <xs:documentation>
          List of classes these influences are for. Leave empty to make it work for all classes. If there are multiple options, the game will choose the first one that matches the class.
        </xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:complexType>

  <xs:complexType name="influencelist">
    <xs:annotation>
      <xs:documentation>
        List of influences, referencable by ID
      </xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="influences" type="influences" minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
    <xs:attribute name="id" type="idstring">
      <xs:annotation>
        <xs:documentation>
          Unique ID
        </xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="name" type="xs:string">
      <xs:annotation>
        <xs:documentation>
          User-readable name
        </xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="description" type="xs:string">
      <xs:annotation>
        <xs:documentation>
          User-readable description
        </xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="icon" type="idstring">
      <xs:annotation>
        <xs:documentation>
          Icon ID override (optional)
        </xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:complexType>

  <xs:element name="influencelistconfigurations">
    <xs:annotation>
      <xs:documentation>
        Document element of influenceconfigurations.xml
      </xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element name="influencelist" type="influencelist" minOccurs="0" maxOccurs="unbounded" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== scev0/x-source/libraries/influenceconfigurations.xml
<?xml version="1.0" encoding="utf-8"?>
<influencelistconfigurations xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xsi:noNamespaceSchemaLocation="influenceconfigurations.xsd">
  <!--Other influences-->

  <influencelist id="emp_missile" name="{20230,2001}" description="{20230,2002}">
    <influences>
      <influence type="disableboost">
        <profile type="continuous" duration="30" />
      </influence>
      <influence type="disabletravel">
        <profile type="continuous" duration="30" />
      </influence>
    </influences>
  </influencelist>

  <influencelist id="region_travel_disrupt" name="{20230,2005}" description="{20230,2006}">
    <influences classes="ship">
      <influence type="disabletravel">
        <profile type="continuous" duration="10" />
      </influence>
    </influences>
  </influencelist>

  <influencelist id="recharge_oxygen">
    <influences classes="spacesuit">
      <influence type="chargeoxygen">
        <profile type="continuous" startvalue="25" duration="1" />
      </influence>
    </influences>
  </influencelist>

  <influencelist id="damage_radiation_slow">
    <influences>
      <influence type="hullshielddamage">
        <profile type="continuous" startvalue="0.01" duration="1" />
      </influence>
    </influences>
  </influencelist>

  <influencelist id="test_speed">
    <influences classes="ship">
      <influence type="disableboost">
        <profile type="continuous" duration="5"/>
      </influence>
      <influence type="maxforwardspeed">
        <profile type="envelope" delay="3" sustainvalue="0.0" sustainduration="2"/>
      </influence>
      <influence type="maxreversespeed">
        <profile type="envelope" delay="3" sustainvalue="0.0" sustainduration="2"/>
      </influence>
    </influences>
  </influencelist>

  <influencelist id="test_accel">
    <influences classes="ship">
      <influence type="disableboost">
        <profile type="continuous" duration="8"/>
      </influence>
      <influence type="forwardacceleration">
        <profile type="envelope" sustainvalue="0.0" sustainduration="8"/>
      </influence>
      <influence type="reverseacceleration">
        <profile type="envelope" sustainvalue="0.0" sustainduration="8"/>
      </influence>
    </influences>
  </influencelist>

  <influencelist id="test_steering">
    <influences classes="ship">
      <!--<influence type="steeringacceleration">-->
      <influence type="maxsteeringspeed">
        <profile type="envelope" sustainvalue="0.0" sustainduration="5"/>
      </influence>
    </influences>
  </influencelist>

  <!--Some examples-->

  <!--<influencelist id="full_example" name="{1234,567890}" description="{1234,567891}" icon="be_ability_emp">
    <influences classes="ship_l ship_xl">
      <influence type="disabletravel">
        <profile type="continuous" duration="10" />
      </influence>
    </influences>
    <influences classes="ship">
      <influence type="disableboost">
        <profile type="continuous" duration="30" />
      </influence>
      <influence type="disabletravel">
        <profile type="continuous" duration="60" />
      </influence>
    </influences>
  </influencelist>-->

  <!--<influencelist id="regular_damage_example">
    <influences>
      <influence type="shieldhulldamage">
        <profile type="ticking" startvalue="75" />
      </influence>
    </influences>
  </influencelist>-->

  <!--<influencelist id="hull_only_damage_example">
    <influences>
      <influence type="hulldamage">
        <profile type="ticking" startvalue="25" />
      </influence>
    </influences>
  </influencelist>-->

  <!--<influencelist id="ticking_damage_over_time_example">
    <influences>
      <influence type="shieldhulldamage">
        <profile type="ticking" startvalue="25" delay="1" amount="5" />
      </influence>
    </influences>
  </influencelist>-->

  <!--<influencelist id="continuous_damage_over_time_example">
    <influences>
      <influence type="shieldhulldamage">
        <profile type="continuous" startvalue="125" duration="5" />
      </influence>
    </influences>
  </influencelist>-->

  <!--<influencelist id="damage_shield_and_slow_down_example">
    <influences>
      <influence type="shielddamage">
        <profile type="ticking" startvalue="150" />
      </influence>
      <influence type="maxforwardspeed">
        <profile type="envelope" startvalue="1" sustainvalue="0.25" endvalue="1" attackduration="0.5" sustainduration="1.5" releaseduration="1.0" />
      </influence>
      <influence type="maxstrafespeed">
        <profile type="envelope" startvalue="1" sustainvalue="0.25" endvalue="1" attackduration="0.5" sustainduration="1.5" releaseduration="1.0" />
      </influence>
      <influence type="maxsteeringspeed">
        <profile type="envelope" startvalue="1" sustainvalue="0.25" endvalue="1" attackduration="0.5" sustainduration="1.5" releaseduration="1.0" />
      </influence>
    </influences>
  </influencelist>-->

  <!--<influencelist id="booster_example">
    <influences>
      -->
  <!--increase max forward, reduce strafing and steering speeds and accelerations-->
  <!--
      <influence type="maxforwardspeed">
        <profile type="envelope" startvalue="1" sustainvalue="4" endvalue="1" attackduration="1.0" sustainduration="4.0" releaseduration="2.0" />
      </influence>
      <influence type="maxstrafespeed">
        <profile type="envelope" startvalue="1" sustainvalue="0.25" endvalue="1" attackduration="1.0" sustainduration="4.0" releaseduration="2.0" />
      </influence>
      <influence type="maxsteeringspeed">
        <profile type="envelope" startvalue="1" sustainvalue="0.25" endvalue="1" attackduration="1.0" sustainduration="4.0" releaseduration="2.0" />
      </influence>
      <influence type="forwardacceleration">
        <profile type="envelope" startvalue="1" sustainvalue="4" endvalue="1" attackduration="1.0" sustainduration="4.0" releaseduration="2.0" />
      </influence>
      <influence type="strafeacceleration">
        <profile type="envelope" startvalue="1" sustainvalue="0.25" endvalue="1" attackduration="1.0" sustainduration="4.0" releaseduration="2.0" />
      </influence>
      <influence type="steeringacceleration">
        <profile type="envelope" startvalue="1" sustainvalue="0.25" endvalue="1" attackduration="1.0" sustainduration="4.0" releaseduration="2.0" />
      </influence>
    </influences>
  </influencelist>-->

</influencelistconfigurations>
